/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MemoizationImport } from './routes/memoization'
import { Route as DataFetchingImport } from './routes/dataFetching'
import { Route as ComponentBuildingImport } from './routes/componentBuilding'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MemoizationRoute = MemoizationImport.update({
  path: '/memoization',
  getParentRoute: () => rootRoute,
} as any)

const DataFetchingRoute = DataFetchingImport.update({
  path: '/dataFetching',
  getParentRoute: () => rootRoute,
} as any)

const ComponentBuildingRoute = ComponentBuildingImport.update({
  path: '/componentBuilding',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/componentBuilding': {
      preLoaderRoute: typeof ComponentBuildingImport
      parentRoute: typeof rootRoute
    }
    '/dataFetching': {
      preLoaderRoute: typeof DataFetchingImport
      parentRoute: typeof rootRoute
    }
    '/memoization': {
      preLoaderRoute: typeof MemoizationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ComponentBuildingRoute,
  DataFetchingRoute,
  MemoizationRoute,
])

/* prettier-ignore-end */
