/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MemoizationImport } from './routes/memoization'
import { Route as ComponentBuildingImport } from './routes/componentBuilding'
import { Route as DogsImport } from './routes/_dogs'
import { Route as DogsDogsImport } from './routes/_dogs/dogs'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MemoizationRoute = MemoizationImport.update({
  path: '/memoization',
  getParentRoute: () => rootRoute,
} as any)

const ComponentBuildingRoute = ComponentBuildingImport.update({
  path: '/componentBuilding',
  getParentRoute: () => rootRoute,
} as any)

const DogsRoute = DogsImport.update({
  id: '/_dogs',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DogsDogsRoute = DogsDogsImport.update({
  path: '/dogs',
  getParentRoute: () => DogsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dogs': {
      preLoaderRoute: typeof DogsImport
      parentRoute: typeof rootRoute
    }
    '/componentBuilding': {
      preLoaderRoute: typeof ComponentBuildingImport
      parentRoute: typeof rootRoute
    }
    '/memoization': {
      preLoaderRoute: typeof MemoizationImport
      parentRoute: typeof rootRoute
    }
    '/_dogs/dogs': {
      preLoaderRoute: typeof DogsDogsImport
      parentRoute: typeof DogsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DogsRoute.addChildren([DogsDogsRoute]),
  ComponentBuildingRoute,
  MemoizationRoute,
])

/* prettier-ignore-end */
