/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MemoizationImport } from './routes/memoization'
import { Route as DogsImport } from './routes/dogs'
import { Route as ComponentBuildingImport } from './routes/componentBuilding'
import { Route as DogsIndexImport } from './routes/dogs/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MemoizationRoute = MemoizationImport.update({
  path: '/memoization',
  getParentRoute: () => rootRoute,
} as any)

const DogsRoute = DogsImport.update({
  path: '/dogs',
  getParentRoute: () => rootRoute,
} as any)

const ComponentBuildingRoute = ComponentBuildingImport.update({
  path: '/componentBuilding',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DogsIndexRoute = DogsIndexImport.update({
  path: '/',
  getParentRoute: () => DogsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/componentBuilding': {
      id: '/componentBuilding'
      path: '/componentBuilding'
      fullPath: '/componentBuilding'
      preLoaderRoute: typeof ComponentBuildingImport
      parentRoute: typeof rootRoute
    }
    '/dogs': {
      id: '/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof DogsImport
      parentRoute: typeof rootRoute
    }
    '/memoization': {
      id: '/memoization'
      path: '/memoization'
      fullPath: '/memoization'
      preLoaderRoute: typeof MemoizationImport
      parentRoute: typeof rootRoute
    }
    '/dogs/': {
      id: '/dogs/'
      path: '/'
      fullPath: '/dogs/'
      preLoaderRoute: typeof DogsIndexImport
      parentRoute: typeof DogsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ComponentBuildingRoute,
  DogsRoute: DogsRoute.addChildren({ DogsIndexRoute }),
  MemoizationRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/componentBuilding",
        "/dogs",
        "/memoization"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/componentBuilding": {
      "filePath": "componentBuilding.tsx"
    },
    "/dogs": {
      "filePath": "dogs.tsx",
      "children": [
        "/dogs/"
      ]
    },
    "/memoization": {
      "filePath": "memoization.tsx"
    },
    "/dogs/": {
      "filePath": "dogs/index.tsx",
      "parent": "/dogs"
    }
  }
}
ROUTE_MANIFEST_END */
